### ISSUE TITLE
Add proper validation for required parameters & for any kind incorrect usage

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-external-api#2]
In the event that a required parameter is excluded, a proper error message should be returned. Same for any improper parameter values.

**Comment by akmiller01** [comment]
@edwinmp I think the only required parameter for most end-points is just the table name. I had considered first performing the query in all_tables to check whether a table is present in the DB before querying it, but that would add a third lookup per indicator. I'll look into better error messages. Do you think the error messages should be delivered in the requested format? Or am I fine to just send plain text as a response?

**Comment by akmiller01** [comment]
Oh plus, in terms of SQL injection, the pg-promise app is actually really good at validating parameters before inserting them into queries: https://vitaly-t.github.io/pg-promise/helpers.TableName.html

**Comment by edwinmp** [comment]
@akmiller01 think the error messages should be in the requested format... consistent.
